module.exports = {
  FeatureName: 'Milo Blocks Accessibility',
  features: [
    {
      tcid: '0',
      name: 'Accessibility Test for Accordion',
      paths: [
        { path: '/drafts/nala/blocks/accordion/accordion', variant: 'default' },
        { path: '/drafts/nala/blocks/accordion/accordion-seo', variant: 'seo' },
        { path: '/drafts/nala/blocks/accordion/accordion-seo-editorial', variant: 'seo' },
      ],
      tags: '@accordion @a13y',
    },
    {
      tcid: '1',
      name: 'Accessibility Test for Carousel',
      paths: [
        { path: '/drafts/nala/blocks/carousel/lightbox', variant: 'Carousel(container)' },
        { path: '/drafts/nala/blocks/carousel/fullpage-carousel', variant: 'Carousel(lightbox)' },
        { path: '/drafts/nala/blocks/carousel/carousel-show-2', variant: 'Carousel Multi slide(show-2)' },
      ],
      tags: '@a13y',
    },
    {
      tcid: '2',
      name: 'Accessibility Test for Action-Item',
      paths: [
        { path: '/drafts/nala/blocks/action-item/action-item-small', variant: 'Action-item (small)' },
        { path: '/drafts/nala/blocks/action-item/action-item-medium', variant: 'Action-item (medium)' },
        { path: '/drafts/nala/blocks/action-item/action-item-large', variant: 'Action-item (large)' },
        { path: '/drafts/nala/blocks/action-item/action-item-center', variant: 'Action-item (center)' },
        { path: '/drafts/nala/blocks/action-item/action-item-rounded', variant: 'Action-item (rounded)' },
        { path: '/drafts/nala/blocks/action-item/action-item-float-button', variant: 'Action-item (float-button)' },
        { path: '/drafts/nala/blocks/action-item/action-scroller', variant: 'Action-item (scroller)' },
        { path: '/drafts/nala/blocks/action-item/action-scroller-navigation', variant: 'Action-item (scroller with navigation)' },
      ],      
      tags: '@a13y',
    },
    {
      tcid: '3',
      name: 'Accessibility Aside',
      paths: [
        { path: '/drafts/nala/blocks/aside/aside-small', variant: 'Aside-Small' },
        { path: '/drafts/nala/blocks/aside/aside-medium', variant: 'Aside-Medium' },
        { path: '/drafts/nala/blocks/aside/aside-large', variant: 'Aside-Large' },
        { path: '/drafts/nala/blocks/aside/aside-split-small-dark', variant: 'Aside-Split-Small-Dark' },
        { path: '/drafts/nala/blocks/aside/aside-split-small-half-dark', variant: 'Aside-Split-Small-Half-Dark' },
        { path: '/drafts/nala/blocks/aside/aside-split-medium', variant: 'Aside-Split-Medium' },
        { path: '/drafts/nala/blocks/aside/aside-split-medium-half', variant: 'Aside-Split-Medium-Half' },
        { path: '/drafts/nala/blocks/aside/aside-split-large', variant: 'Aside-Split-Large' },
        { path: '/drafts/nala/blocks/aside/aside-split-large-half-dark', variant: 'Aside-Split-Large-Half-Dark' },
        { path: '/drafts/nala/blocks/aside/aside-inline', variant: 'Aside-Inline' },
        { path: '/drafts/nala/blocks/aside/aside-inline-dark', variant: 'Aside-Inline-Dark' },
        { path: '/drafts/nala/blocks/aside/aside-notification-extrasmall-dark', variant: 'Aside-Notif-Extra-Small-Dark' },
        { path: '/drafts/nala/blocks/aside/aside-notification-small', variant: 'Aside-Notif-Small' },
        { path: '/drafts/nala/blocks/aside/aside-notification-medium', variant: 'Aside-Notif-Medium' },
        { path: '/drafts/nala/blocks/aside/aside-notification-medium-center', variant: 'Aside-Notif-Medium-Center' },
        { path: '/drafts/nala/blocks/aside/aside-notification-large', variant: 'Aside-Notif-Large' },
        { path: '/drafts/nala/blocks/aside/aside-notification-large-center', variant: 'Aside-Notif-Large-Center' },
      ],        
      tags: '@a13y',
    },
    {
      tcid: '4',
      name: 'Accessibility Test for Action-Item',
      paths: [
        { path: '/drafts/nala/blocks/action-item/action-item-small', variant: 'Action-item (small)' },
        { path: '/drafts/nala/blocks/action-item/action-item-medium', variant: 'Action-item (medium)' },
        { path: '/drafts/nala/blocks/action-item/action-item-large', variant: 'Action-item (large)' },
        { path: '/drafts/nala/blocks/action-item/action-item-center', variant: 'Action-item (center)' },
        { path: '/drafts/nala/blocks/action-item/action-item-rounded', variant: 'Action-item (rounded)' },
        { path: '/drafts/nala/blocks/action-item/action-item-float-button', variant: 'Action-item (float-button)' },
        { path: '/drafts/nala/blocks/action-item/action-scroller', variant: 'Action-item (scroller)' },
        { path: '/drafts/nala/blocks/action-item/action-scroller-navigation', variant: 'Action-item (scroller with navigation)' },
      ],      
      tags: '@a13y',
    },
    {
      tcid: '5',
      name: 'Accessibility Test for Card',
      paths: [
        { path: '/drafts/nala/blocks/chart/chart-area-green-border', variant: 'Chart (area, green, border)' },
        { path: '/drafts/nala/blocks/chart/chart-bar-border', variant: 'Chart (bar, border)' },
        { path: '/drafts/nala/blocks/chart/chart-column-border', variant: 'Chart (column, border)' },
        { path: '/drafts/nala/blocks/chart/chart-donut-border', variant: 'Chart (donut, border)' },
        { path: '/drafts/nala/blocks/chart/chart-line-border', variant: 'Chart (line, border)' },
        { path: '/drafts/nala/blocks/chart/chart-oversized-number-border', variant: 'Chart (oversized-number, border)' },
        { path: '/drafts/nala/blocks/chart/chart-pie-border', variant: 'Chart (pie, border)' },
      ],           
      tags: '@a13y',
    },
    {
      tcid: '6',
      name: 'Accessibility Test for Columns',
      paths: [
        { path: '/drafts/nala/blocks/columns/columns', variant: 'Columns' },
        { path: '/drafts/nala/blocks/columns/columns-contained', variant: 'Columns (contained)' },
        { path: '/drafts/nala/blocks/columns/columns-contained-middle', variant: 'Columns (contained,middle)' },
        { path: '/drafts/nala/blocks/columns/columns-table', variant: 'Columns (table)' },
        { path: '/drafts/nala/blocks/columns/columns-contained-table', variant: 'Columns (contained,table)' },
      ],               
      tags: '@a13y',
    },
    {
      tcid: '7',
      name: 'Accessibility Test Figure',
      paths: [
        { path: '/drafts/nala/blocks/figure/image-with-caption', variant: 'Image with caption' },
        { path: '/drafts/nala/blocks/figure/multiple-images-with-captions', variant: 'Multiple images with caption' },
      ],                             
      tags: '@a13y',
    },    
    {
      tcid: '8',
      name: 'Accessibility Test HowTo',
      paths: [
        { path: '/drafts/nala/blocks/howto/how-to', variant: 'HowTo' },
        { path: '/drafts/nala/blocks/howto/how-to-large', variant: 'HowTo large Image' },
        { path: '/drafts/nala/blocks/howto/how-to-seo', variant: 'HowTo SEO' },
      ],                    
      tags: '@a13y',
    },
    {
      tcid: '9',
      name: 'Accessibility Test for Icon',
      paths: [
        { path: '/drafts/nala/blocks/icon/icon-fullwidth-medium', variant: 'Icon block (fullwidth, medium)' },
        { path: '/drafts/nala/blocks/icon/fullwidth-medium-intro', variant: 'Icon block (fullwidth, medium, intro)' },
        { path: '/drafts/nala/blocks/icon/fullwidth-large', variant: 'Icon block (fullwidth,large)' },
      ],                            
      tags: '@a13y',
    },
    {
      tcid: '10',
      name: 'Accessibility Test for Marquee',
      paths: [
        { path: '/drafts/nala/blocks/marquee/marquee-light', variant: 'Marquee (light)' },
        { path: '/drafts/nala/blocks/marquee/marquee-light-xxl-button', variant: 'Marquee (light xxl-button)' },
        { path: '/drafts/nala/blocks/marquee/marquee-small', variant: 'Marquee (small)' },
        { path: '/drafts/nala/blocks/marquee/marquee-small-light', variant: 'Marquee (small,light)' },
        { path: '/drafts/nala/blocks/marquee/marquee-large', variant: 'Marquee (large)' },
        { path: '/drafts/nala/blocks/marquee/marquee-large-light', variant: 'Marquee (large,light)' },
        { path: '/drafts/nala/blocks/marquee/marquee-large-standard', variant: 'Marquee (large,standard)' },
        { path: '/drafts/nala/blocks/marquee/marquee-large-compact', variant: 'Marquee (large,compact)' },
        { path: '/drafts/nala/blocks/marquee/marquee-quiet', variant: 'Marquee (quiet)' },
        { path: '/drafts/nala/blocks/marquee/marquee-inline', variant: 'Marquee (inline)' },
        { path: '/drafts/nala/blocks/marquee/marquee-split-small', variant: 'Marquee (split,small)' },
        { path: '/drafts/nala/blocks/marquee/marquee-split-large', variant: 'Marquee (split,large)' },
        { path: '/drafts/nala/blocks/marquee/marquee-split-one-third-large-light', variant: 'Marquee (split,one-third,large,light)' },
        { path: '/drafts/nala/blocks/marquee/marquee-split-one-third', variant: 'Marquee (split,one-third)' },
        { path: '/drafts/nala/blocks/marquee/marquee-split-one-third-small-light', variant: 'Marquee (split,one-third,small,light)' },
        { path: '/drafts/nala/blocks/marquee/marquee-small-background-video', variant: 'Marquee small (background video playsinline)' },
        { path: '/drafts/nala/blocks/marquee/marquee-large-desktop-video-autoplay', variant: 'Marquee large (background video playsinline desktop)' },
        { path: '/drafts/nala/blocks/marquee/video-autoplay-loop-once', variant: 'Marquee large (background video playsinline loop once)' },
        { path: '/drafts/nala/blocks/marquee/marquee-background-image-focal-point', variant: 'Marquee background image focal point' },
      ],                                 
      tags: '@a13y',
    },
    {
      tcid: '11',
      name: 'Accessibility Test for Marquee-Anchors',
      paths: [
        { path: '/drafts/nala/blocks/marquee/marquee-anchors', variant: 'Marquee Anchors' },
        { path: '/drafts/nala/blocks/marquee/marquee-anchors-transparent', variant: 'Marquee Anchors (Transparent)' },
      ],                                  
      tags: '@a13y',
    },
    {
      tcid: '12',
      name: 'Accessibility Test for Media',
      paths: [
        { path: '/drafts/nala/blocks/media/media-small', variant: 'Media (small)' },
        { path: '/drafts/nala/blocks/media/media', variant: 'Media' },
        { path: '/drafts/nala/blocks/media/media-large-dark', variant: 'media (large, dark)' },
        { path: '/drafts/nala/blocks/media/media-video-autoplay-infinite-loop', variant: 'media (large, dark) video, autoplay infinite looping' },
        { path: '/drafts/nala/blocks/media/media-video-autoplay-loop-once', variant: 'media video, autoplay loop once' },
      ],                                       
      tags: '@a13y',
    },
    {
      tcid: '13',
      name: 'Accessibility Test for Merchcard',
      paths: [
        { path: '/drafts/nala/blocks/merch-card/merch-card-segment', variant: 'Merch-card (Segment)' },
        { path: '/drafts/nala/blocks/merch-card/merch-card-segment-with-badge', variant: 'Merch-card (Segment) with Badge' },
        { path: '/drafts/nala/blocks/merch-card/merch-card-special-offers', variant: 'Merch-card (special-offers)' },
        { path: '/drafts/nala/blocks/merch-card/merch-card-special-offers-with-badge', variant: 'Merch-card (special-offers) with badge' },
        { path: '/drafts/nala/blocks/merch-card/merch-cards-plans', variant: 'Merch-card (plans)' },
        { path: '/drafts/nala/blocks/merch-card/merch-card-plans-with-badge', variant: 'Merch-card (plans) with badge' },
        { path: '/drafts/nala/blocks/merch-card/merch-card-plans-secure', variant: 'Merch-card (plans, secure)' },
        { path: '/drafts/nala/blocks/merch-card/merch-cards-plans-secure-with-badge', variant: 'Merch-card (plans, secure) with badge' },
        { path: '/drafts/nala/blocks/merch-card/merch-cards-catalog', variant: 'Merch-card (catalog)' },
        { path: '/drafts/nala/blocks/merch-card/march-cards-catalog-with-badge', variant: 'Merch-card (catalog) with badge' },
        { path: '/drafts/nala/blocks/merch-card/merch-cards-catalog-with-more-info-and-badge', variant: 'Merch-card (catalog) with more info and badge' },
      ],                                           
      tags: '@a13y',
    },
    {
      tcid: '14',
      name: 'Accessibility Test for Modal',
      paths: [
        { path: '/drafts/nala/blocks/modal/modal-text-intro', variant: 'Modal Text' },
        { path: '/drafts/nala/blocks/modal/modal-media', variant: 'Modal Media' },
        { path: '/drafts/nala/blocks/modal/modal-autoplay-video', variant: 'Modal Autoplay Video' },
      ],                                                
      tags: '@a13y',
    },
    {
      tcid: '15',
      name: 'Accessibility Test for Quote',
      paths: [
        { path: '/drafts/nala/blocks/quote/quote', variant: 'Quote' },
        { path: '/drafts/nala/blocks/quote/quote-contained', variant: 'Quote (contained)' },
        { path: '/drafts/nala/blocks/quote/quote-inline-contained', variant: 'Quote (inline, contained)' },
        { path: '/drafts/nala/blocks/quote/quote-borders-contained', variant: 'Quote (borders, contained)' },
        { path: '/drafts/nala/blocks/quote/quote-contained-align-right', variant: 'Quote (contained, align-right)' },
        { path: '/drafts/nala/blocks/quote/quote-xl-spaced', variant: 'Quote (xl-spaced)' },
      ],                                                  
      tags: '@a13y',
    },
    {
      tcid: '16',
      name: 'Accessibility Test for Review',
      paths: [
        { path: '/drafts/nala/blocks/review/review', variant: 'Review low (rating 4)' },
        { path: '/drafts/nala/blocks/review/review', variant: 'Review low (rating 2)' },
      ],                                                       
      tags: '@a13y',
    },
    {
      tcid: '17',
      name: 'Accessibility Test for Table',
      paths: [
        { path: '/drafts/nala/blocks/table/table', variant: 'Table (default)' },
        { path: '/drafts/nala/blocks/table/table-hightlight', variant: 'Table (highlight)' },
        { path: '/drafts/nala/blocks/table/table-sticky', variant: 'Table (sticky)' },
        { path: '/drafts/nala/blocks/table/table-highlight-collapse-sticky', variant: 'Table (highlight, collapse, sticky)' },
        { path: '/drafts/nala/blocks/table/table-merch', variant: 'Table (merch)' },
      ],                                                           
      tags: '@a13y',
    },
    {
      tcid: '18',
      name: 'Accessibility Test for Tabs',
      paths: [
        { path: '/drafts/nala/blocks/tabs/tabs-xl-spacing', variant: 'Tabs (xl-spacing)' },
        { path: '/drafts/nala/blocks/tabs/tabs-quiet-dark-center', variant: 'Tabs (Quiet, Dark, Center)' },
        { path: '/drafts/nala/blocks/tabs/tabs-scrolling', variant: 'Tabs scrolling' },
      ],                                                               
      tags: '@a13y',
    },
    {
      tcid: '19',
      name: 'Accessibility Test for Text',
      paths: [
        { path: '/drafts/nala/blocks/text/text', variant: 'Text' },
        { path: '/drafts/nala/blocks/text/text-intro', variant: 'Text (intro)' },
        { path: '/drafts/nala/blocks/text/text-full-width', variant: 'Text (full-width)' },
        { path: '/drafts/nala/blocks/text/text-full-width-large', variant: 'Text (full-width, large)' },
        { path: '/drafts/nala/blocks/text/text-long-form-large', variant: 'Text (long-form, large)' },
        { path: '/drafts/nala/blocks/text/text-inset-medium-m-spacing', variant: 'Text (inset, medium, m-spacing)' },
        { path: '/drafts/nala/blocks/text/text-legal', variant: 'Text (legal)' },
        { path: '/drafts/nala/blocks/text/text-link-farm', variant: 'Text (link-farm)' },
      ],                                                                    
      tags: '@a13y',
    },
    {
      tcid: '20',
      name: 'Accessibility Test for Video',
      paths: [
        { path: '/drafts/nala/blocks/video/default-video', variant: 'Video Default' },
        { path: '/drafts/nala/blocks/video/video-autoplay-loop', variant: 'Video autoplay loop' },
        { path: '/drafts/nala/blocks/video/autoplay-loop-once', variant: 'Video autoplay loop once' },
        { path: '/drafts/nala/blocks/video/video-hover-play', variant: 'Video hover play' },
        { path: '/drafts/nala/blocks/video/mpc-video', variant: 'MPC Video' },
        { path: '/drafts/nala/blocks/video/mpc-video-autoplay-looping', variant: 'MPC Video Autoplay Looping' },
        { path: '/drafts/nala/blocks/video/youtube-video', variant: 'Youtube Video' },
        { path: '/drafts/nala/blocks/video/fragments-modal-video-autoplay', variant: 'Fragment Modal video inline' },
        { path: '/drafts/nala/blocks/video/modal-video-with-cards', variant: 'Modal video with cards' },
      ],                                                                        
      tags: '@a13y',
    },
    {
      tcid: '21',
      name: 'Accessibility Test for Zpattern',
      paths: [
        { path: '/drafts/nala/blocks/zpattern/z-pattern', variant: 'ZPattern' },
        { path: '/drafts/nala/blocks/zpattern/z-pattern-small', variant: 'ZPattern (small)' },
        { path: '/drafts/nala/blocks/zpattern/z-pattern-large', variant: 'Zpattern (large)' },
        { path: '/drafts/nala/blocks/zpattern/z-pattern-dark', variant: 'Zpattern (dark)' },
      ],                                                                            
      tags: '@a13y',
    },
    {
      tcid: '22',
      name: 'Accessibility Test for Commerce',
      paths: [
        { path: '/drafts/nala/features/commerce/prices-with-term', variant: 'Commerce-Price-Term' },
        { path: '/drafts/nala/features/commerce/prices-with-term-unit', variant: 'Commerce-Price-Unit-Term' },
        { path: '/drafts/nala/features/commerce/prices-with-term-unit-taxlabel', variant: 'Commerce-Price-Taxlabel-Unit-Term' },
        { path: '/drafts/nala/features/commerce/promo-placeholders', variant: 'Commerce-Promo' },
        { path: '/drafts/nala/features/commerce/checkout-links', variant: 'Commerce-Upgrade-Entitlement' },
        { path: '/drafts/nala/features/commerce/checkout-links', variant: 'Commerce-Download-Entitlement' },
        { path: '/docs/library/kitchen-sink/merch-card', variant: 'Commerce-KitchenSink-Smoke' },
        { path: '/de/drafts/nala/features/commerce/promo-placeholders', variant: 'Commerce-DE' },
        { path: '/drafts/nala/features/commerce/promo-old-price', variant: 'Commerce-Old-Promo' },
        { path: '/uk/drafts/nala/features/commerce/promo-placeholders', variant: 'Commerce-GB' },
      ],                                                                               
      tags: '@a13y',
    },
    {
      tcid: '23',
      name: 'Accessibility Test for Promotions',
      paths: [
        { path: '/drafts/nala/features/commerce/prices-with-term', variant: 'Commerce-Price-Term' },
        { path: '/drafts/nala/features/commerce/prices-with-term-unit', variant: 'Commerce-Price-Unit-Term' },
        { path: '/drafts/nala/features/commerce/prices-with-term-unit-taxlabel', variant: 'Commerce-Price-Taxlabel-Unit-Term' },
        { path: '/drafts/nala/features/commerce/promo-placeholders', variant: 'Commerce-Promo' },
        { path: '/drafts/nala/features/commerce/checkout-links', variant: 'Commerce-Upgrade-Entitlement' },
        { path: '/drafts/nala/features/commerce/checkout-links', variant: 'Commerce-Download-Entitlement' },
        { path: '/docs/library/kitchen-sink/merch-card', variant: 'Commerce-KitchenSink-Smoke' },
        { path: '/de/drafts/nala/features/commerce/promo-placeholders', variant: 'Commerce-DE' },
        { path: '/drafts/nala/features/commerce/promo-old-price', variant: 'Commerce-Old-Promo' },
        { path: '/uk/drafts/nala/features/commerce/promo-placeholders', variant: 'Commerce-GB' },
      ],                                                                               
      tags: '@a13y',
    },                                                                                           
  ],
};
