name: Run Nala Accessibility Tests

on:
  workflow_dispatch:
    inputs:
      input_url:
        description: "The URL to run accessibility tests on"
        required: false
        default: "https://www.adobe.com/acrobat/personal-document-management.html"
  push:
    branches:
      - nala-a11y  # Only runs on push events to this branch

jobs:
  run-accessibility-tests:
    name: Running Accessibility Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare URLs
        run: |
          INPUT_URL="${{ github.event.input.input_url }}"
          if [ -z "$INPUT_URL" ]; then
            INPUT_URL="https://milo.adobe.com/"
          fi
          echo "Using input url: ${{ github.event.input.input_url }}"
          echo "INPUT_URLS=${{ github.event.input.input_url }}" >> $GITHUB_ENV

      - name: Debug URLs
        run: |
          echo "Final URLs: ${{ env.INPUT_URLS }}"

      - name: Create report directory and store in environment variable
        run: |
          REPORT_DIR=$(pwd)/nala-reports
          mkdir -p "$REPORT_DIR"
          echo "REPORT_DIR=$REPORT_DIR" >> $GITHUB_ENV
          echo "Created report directory at $REPORT_DIR"

      - name: Set execute permission for a11y.run.sh
        run: chmod +x ./nala/utils/a11y.run.sh

      - name: Run Accessibility Tests via a11y.run.sh
        run: ./nala/utils/a11y.run.sh
        continue-on-error: true

      - name: Copy the generated accessibility report
        run: |
          mkdir -p reports
          cp -r "$REPORT_DIR"/* reports/

      - name: Upload the report to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nala-accessibility-test-report
          path: reports/*
          retention-days: 1

      - name: Display artifact URL
        run: |
          echo "View and download the accessibility report artifact here:"
          echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifact"
