name: Nala Accessibility Tests

on:
  push:
    branches:
      - nala-a11y  # Only runs on push events to this branch

jobs:
  run-accessibility-tests:
    name: Running Accessibility Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare URLs
        run: |
          # For push events, we use a default URL
          echo "Triggered by a push event. Using default URL."
          echo "INPUT_URLS=https://www.adobe.com/acrobat/personal-document-management.html" >> $GITHUB_ENV

      - name: Debug URLs
        run: |
          echo "Final URLs: ${{ env.INPUT_URLS }}"

      - name: Set execute permission for a11y.run.sh
        run: chmod +x ./nala/utils/a11y.run.sh

      - name: Run Accessibility Tests via a11y.run.sh
        run: ./nala/utils/a11y.run.sh

      - name: Checkout nala-a11y-results branch in your fork
        uses: actions/checkout@v4
        with:
          repository: skumar09/milo
          ref: nala-a11y-results
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy the generated accessibility report
        run: |
          mkdir -p reports
          cp -r nala-report-a11y/manual-reports/* reports/

      - name: Commit and push the accessibility report to nala-a11y-results branch
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add reports/
          git commit -m "Update accessibility report [skip ci]"
          git push origin nala-a11y-results
