name: Nala Accessibility Tests

on:
  workflow_dispatch:  # Workflow to be triggered manually
    inputs:
      urls:
        description: 'Comma-separated list of URLs to run accessibility tests on'
        required: false
        default: ''
      urls_file:
        description: 'File containing URLs (one URL per line) to run accessibility tests on'
        required: false
  push:
    branches:
      - main
      - stage
      - nala-a11y

jobs:
  run-accessibility-tests:
    name: Running Accessibility Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare URLs
        run: |
          # Check if URLs input was provided
          if [ "${{ github.event.inputs.urls }}" != "" ]; then
            echo "Using manually provided URLs: ${{ github.event.inputs.urls }}"
            echo "INPUT_URLS=${{ github.event.inputs.urls }}" >> $GITHUB_ENV
          fi

          # Check if URLs file was provided
          if [ "${{ github.event.inputs.urls_file }}" != "" ]; then
            echo "Using URLs from the file: ${{ github.event.inputs.urls_file }}"
            cat "${{ github.event.inputs.urls_file }}" > urls_from_file.txt
            echo "INPUT_URLS=$(cat urls_from_file.txt | tr '\n' ',' | sed 's/,$//')" >> $GITHUB_ENV
          fi

      - name: Set execute permission for a11y.run.sh
        run: chmod +x ./nala/utils/a11y.run.sh

      - name: Run Accessibility Tests via a11y.run.sh
        run: ./nala/utils/a11y.run.sh

      - name: Checkout nala-a11y-results branch in your fork
        uses: actions/checkout@v4
        with:
          repository: skumar09/milo
          ref: nala-a11y-results
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy the generated accessibility report
        run: |
          mkdir -p reports
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            cp -r nala-report-a11y/pr-reports/* reports/
          else
            cp -r nala-report-a11y/manual-reports/* reports/
          fi

      - name: Commit and push the accessibility report to nala-a11y-results branch
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add reports/
          git commit -m "Update accessibility report [skip ci]"
          git push origin nala-a11y-results
