name: Run Nala Accessibility Tests

on:
  workflow_dispatch:
    inputs:
      run_name:
        description: "Workflow name"
        required: false
        default: "Nala Accessibility Test Run for Milo" 
      input_url:
        description: "The URL to run accessibility tests on"
        required: false
        default: "https://www.adobe.com/acrobat/personal-document-management.html"
      test_scope:
        description: "Entire Page or Section/block (ex: .accordion.container OR .section)"
        required: false
        default: "body"
      wcag_tags:
        description: "WCAG tags for the accessibility tests (e.g., 'wcag2a', 'wcag2aa', 'wcag2aaa')"
        required: false
        default: "wcag2a, wcag2aa, wcag21a, wcag21aa"
      max_violations:
        description: "Maximum allowed accessibility violations"
        required: false
        default: 0

jobs:
  run-accessibility-tests:
    name: Running Accessibility Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare environment variables
        run: |
          echo "INPUT_URL=${{ github.event.inputs.input_url }}" >> $GITHUB_ENV
          echo "TEST_SCOPE=${{ github.event.inputs.test_scope }}" >> $GITHUB_ENV
          echo "WCAG_TAGS=${{ github.event.inputs.wcag_tags }}" >> $GITHUB_ENV
          echo "MAX_VIOLATIONS=${{ github.event.inputs.max_violations }}" >> $GITHUB_ENV
          echo "MILO_LIBS=${{ secrets.MILO_LIBS }}" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: |
          echo "URL: ${{ env.INPUT_URL }}"
          echo "Test Scope: ${{ env.TEST_SCOPE }}"
          echo "WCAG Tags: ${{ env.WCAG_TAGS }}"
          echo "Max Violations: ${{ env.MAX_VIOLATIONS }}"

      - name: Create report directory and store in environment variable
        run: |
          REPORT_DIR=$(pwd)/nala-reports
          mkdir -p "$REPORT_DIR"
          echo "REPORT_DIR=$REPORT_DIR" >> $GITHUB_ENV
          echo "Created report directory at $REPORT_DIR"

      - name: Set execute permission for a11y.run.sh
        run: chmod +x ./nala/utils/a11y.run.sh

      - name: Run Accessibility Tests via a11y.run.sh
        run: ./nala/utils/a11y.run.sh
        continue-on-error: true

      - name: Copy the generated accessibility report
        run: |
          mkdir -p reports
          cp -r "$REPORT_DIR"/* reports/

      - name: Get the generated report name
        id: get-report-name
        run: |
          report_name=$(ls "$REPORT_DIR"/nala-a11y-report-*.html)
          echo "REPORT_NAME=$report_name" >> $GITHUB_ENV
          echo "::set-output name=report_name::$report_name"          

      - name: Upload the report to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nala-accessibility-test-report
          path: reports/*
          retention-days: 1

      - name: Display artifact URL
        run: |
          echo "View and download the accessibility report artifact here:"
          echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifact"
      
      - name: Send HTML report to Slack via Nala-Result
        run: |
          curl -F file=@reports/${{ env.REPORT_NAME }} \
               -F channels=C04KNA6KAAV
               -F token=$SLACK_BOT_TOKEN \
               -F title="Nala Accessibility Test Report" \
               -F initial_comment="Here is the latest Nala Accessibility Test Report in HTML format" \
               https://slack.com/api/files.upload
        env:
          SLACK_BOT_TOKEN: ${{ secrets.NALA_SLACK_OAUTH_TOKEN}}

